// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `proto/message.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct KPMessage {
    // message fields
    pub action: super::keys::EventMessageAction,
    pub body: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a KPMessage {
    fn default() -> &'a KPMessage {
        <KPMessage as ::protobuf::Message>::default_instance()
    }
}

impl KPMessage {
    pub fn new() -> KPMessage {
        ::std::default::Default::default()
    }

    // .KPProto.EventMessageAction action = 1;


    pub fn get_action(&self) -> super::keys::EventMessageAction {
        self.action
    }
    pub fn clear_action(&mut self) {
        self.action = super::keys::EventMessageAction::EVENT_MESSAGE_ACTION_PLAYER_STARTED;
    }

    // Param is passed by value, moved
    pub fn set_action(&mut self, v: super::keys::EventMessageAction) {
        self.action = v;
    }

    // string body = 2;


    pub fn get_body(&self) -> &str {
        &self.body
    }
    pub fn clear_body(&mut self) {
        self.body.clear();
    }

    // Param is passed by value, moved
    pub fn set_body(&mut self, v: ::std::string::String) {
        self.body = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_body(&mut self) -> &mut ::std::string::String {
        &mut self.body
    }

    // Take field
    pub fn take_body(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.body, ::std::string::String::new())
    }
}

impl ::protobuf::Message for KPMessage {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.action, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.body)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.action != super::keys::EventMessageAction::EVENT_MESSAGE_ACTION_PLAYER_STARTED {
            my_size += ::protobuf::rt::enum_size(1, self.action);
        }
        if !self.body.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.body);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.action != super::keys::EventMessageAction::EVENT_MESSAGE_ACTION_PLAYER_STARTED {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.action))?;
        }
        if !self.body.is_empty() {
            os.write_string(2, &self.body)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> KPMessage {
        KPMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::keys::EventMessageAction>>(
                "action",
                |m: &KPMessage| { &m.action },
                |m: &mut KPMessage| { &mut m.action },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "body",
                |m: &KPMessage| { &m.body },
                |m: &mut KPMessage| { &mut m.body },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<KPMessage>(
                "KPMessage",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static KPMessage {
        static instance: ::protobuf::rt::LazyV2<KPMessage> = ::protobuf::rt::LazyV2::INIT;
        instance.get(KPMessage::new)
    }
}

impl ::protobuf::Clear for KPMessage {
    fn clear(&mut self) {
        self.action = super::keys::EventMessageAction::EVENT_MESSAGE_ACTION_PLAYER_STARTED;
        self.body.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for KPMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KPMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct KPPrompt {
    // message fields
    pub action: super::keys::EventPromptAction,
    pub body: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a KPPrompt {
    fn default() -> &'a KPPrompt {
        <KPPrompt as ::protobuf::Message>::default_instance()
    }
}

impl KPPrompt {
    pub fn new() -> KPPrompt {
        ::std::default::Default::default()
    }

    // .KPProto.EventPromptAction action = 1;


    pub fn get_action(&self) -> super::keys::EventPromptAction {
        self.action
    }
    pub fn clear_action(&mut self) {
        self.action = super::keys::EventPromptAction::EVENT_PROMPT_ACTION_PLAYER_STOP;
    }

    // Param is passed by value, moved
    pub fn set_action(&mut self, v: super::keys::EventPromptAction) {
        self.action = v;
    }

    // string body = 2;


    pub fn get_body(&self) -> &str {
        &self.body
    }
    pub fn clear_body(&mut self) {
        self.body.clear();
    }

    // Param is passed by value, moved
    pub fn set_body(&mut self, v: ::std::string::String) {
        self.body = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_body(&mut self) -> &mut ::std::string::String {
        &mut self.body
    }

    // Take field
    pub fn take_body(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.body, ::std::string::String::new())
    }
}

impl ::protobuf::Message for KPPrompt {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.action, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.body)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.action != super::keys::EventPromptAction::EVENT_PROMPT_ACTION_PLAYER_STOP {
            my_size += ::protobuf::rt::enum_size(1, self.action);
        }
        if !self.body.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.body);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.action != super::keys::EventPromptAction::EVENT_PROMPT_ACTION_PLAYER_STOP {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.action))?;
        }
        if !self.body.is_empty() {
            os.write_string(2, &self.body)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> KPPrompt {
        KPPrompt::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::keys::EventPromptAction>>(
                "action",
                |m: &KPPrompt| { &m.action },
                |m: &mut KPPrompt| { &mut m.action },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "body",
                |m: &KPPrompt| { &m.body },
                |m: &mut KPPrompt| { &mut m.body },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<KPPrompt>(
                "KPPrompt",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static KPPrompt {
        static instance: ::protobuf::rt::LazyV2<KPPrompt> = ::protobuf::rt::LazyV2::INIT;
        instance.get(KPPrompt::new)
    }
}

impl ::protobuf::Clear for KPPrompt {
    fn clear(&mut self) {
        self.action = super::keys::EventPromptAction::EVENT_PROMPT_ACTION_PLAYER_STOP;
        self.body.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for KPPrompt {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KPPrompt {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13proto/message.proto\x12\x07KPProto\x1a\x10proto/keys.proto\"T\n\tK\
    PMessage\x123\n\x06action\x18\x01\x20\x01(\x0e2\x1b.KPProto.EventMessage\
    ActionR\x06action\x12\x12\n\x04body\x18\x02\x20\x01(\tR\x04body\"R\n\x08\
    KPPrompt\x122\n\x06action\x18\x01\x20\x01(\x0e2\x1a.KPProto.EventPromptA\
    ctionR\x06action\x12\x12\n\x04body\x18\x02\x20\x01(\tR\x04bodyB.Z,github\
    .com/bytelang/kplayer/types/core/protoJ\xc8\x02\n\x06\x12\x04\0\0\x10\
    \x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x10\n\
    \t\n\x02\x03\0\x12\x03\x04\0\x1a\n\x08\n\x01\x08\x12\x03\x06\0C\n\t\n\
    \x02\x08\x0b\x12\x03\x06\0C\n\n\n\x02\x04\0\x12\x04\x08\0\x0b\x01\n\n\n\
    \x03\x04\0\x01\x12\x03\x08\x08\x11\n\x0b\n\x04\x04\0\x02\0\x12\x03\t\x02\
    \x20\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\t\x02\x14\n\x0c\n\x05\x04\0\x02\
    \0\x01\x12\x03\t\x15\x1b\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\t\x1e\x1f\n\
    \x0b\n\x04\x04\0\x02\x01\x12\x03\n\x02\x12\n\x0c\n\x05\x04\0\x02\x01\x05\
    \x12\x03\n\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\n\t\r\n\x0c\n\
    \x05\x04\0\x02\x01\x03\x12\x03\n\x10\x11\n\n\n\x02\x04\x01\x12\x04\r\0\
    \x10\x01\n\n\n\x03\x04\x01\x01\x12\x03\r\x08\x10\n\x0b\n\x04\x04\x01\x02\
    \0\x12\x03\x0e\x02\x1f\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03\x0e\x02\x13\
    \n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x0e\x14\x1a\n\x0c\n\x05\x04\x01\
    \x02\0\x03\x12\x03\x0e\x1d\x1e\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\x0f\
    \x02\x12\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x0f\x02\x08\n\x0c\n\x05\
    \x04\x01\x02\x01\x01\x12\x03\x0f\t\r\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\
    \x03\x0f\x10\x11b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
