// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `proto/msg/msg_plugin.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct MessagePlugin {
    // message fields
    pub path: ::std::string::String,
    pub unique: ::std::string::String,
    pub name: ::std::string::String,
    pub author: ::std::string::String,
    pub media_type: i32,
    pub sub_count: i32,
    pub params: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MessagePlugin {
    fn default() -> &'a MessagePlugin {
        <MessagePlugin as ::protobuf::Message>::default_instance()
    }
}

impl MessagePlugin {
    pub fn new() -> MessagePlugin {
        ::std::default::Default::default()
    }

    // string path = 1;


    pub fn get_path(&self) -> &str {
        &self.path
    }
    pub fn clear_path(&mut self) {
        self.path.clear();
    }

    // Param is passed by value, moved
    pub fn set_path(&mut self, v: ::std::string::String) {
        self.path = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_path(&mut self) -> &mut ::std::string::String {
        &mut self.path
    }

    // Take field
    pub fn take_path(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.path, ::std::string::String::new())
    }

    // string unique = 2;


    pub fn get_unique(&self) -> &str {
        &self.unique
    }
    pub fn clear_unique(&mut self) {
        self.unique.clear();
    }

    // Param is passed by value, moved
    pub fn set_unique(&mut self, v: ::std::string::String) {
        self.unique = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_unique(&mut self) -> &mut ::std::string::String {
        &mut self.unique
    }

    // Take field
    pub fn take_unique(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.unique, ::std::string::String::new())
    }

    // string name = 3;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // string author = 4;


    pub fn get_author(&self) -> &str {
        &self.author
    }
    pub fn clear_author(&mut self) {
        self.author.clear();
    }

    // Param is passed by value, moved
    pub fn set_author(&mut self, v: ::std::string::String) {
        self.author = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_author(&mut self) -> &mut ::std::string::String {
        &mut self.author
    }

    // Take field
    pub fn take_author(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.author, ::std::string::String::new())
    }

    // int32 media_type = 5;


    pub fn get_media_type(&self) -> i32 {
        self.media_type
    }
    pub fn clear_media_type(&mut self) {
        self.media_type = 0;
    }

    // Param is passed by value, moved
    pub fn set_media_type(&mut self, v: i32) {
        self.media_type = v;
    }

    // int32 sub_count = 6;


    pub fn get_sub_count(&self) -> i32 {
        self.sub_count
    }
    pub fn clear_sub_count(&mut self) {
        self.sub_count = 0;
    }

    // Param is passed by value, moved
    pub fn set_sub_count(&mut self, v: i32) {
        self.sub_count = v;
    }

    // repeated .KPProto.Msg.MessagePlugin.ParamsEntry params = 7;


    pub fn get_params(&self) -> &::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &self.params
    }
    pub fn clear_params(&mut self) {
        self.params.clear();
    }

    // Param is passed by value, moved
    pub fn set_params(&mut self, v: ::std::collections::HashMap<::std::string::String, ::std::string::String>) {
        self.params = v;
    }

    // Mutable pointer to the field.
    pub fn mut_params(&mut self) -> &mut ::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &mut self.params
    }

    // Take field
    pub fn take_params(&mut self) -> ::std::collections::HashMap<::std::string::String, ::std::string::String> {
        ::std::mem::replace(&mut self.params, ::std::collections::HashMap::new())
    }
}

impl ::protobuf::Message for MessagePlugin {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.path)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.unique)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.author)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.media_type = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.sub_count = tmp;
                },
                7 => {
                    ::protobuf::rt::read_map_into::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(wire_type, is, &mut self.params)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.path.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.path);
        }
        if !self.unique.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.unique);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.name);
        }
        if !self.author.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.author);
        }
        if self.media_type != 0 {
            my_size += ::protobuf::rt::value_size(5, self.media_type, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.sub_count != 0 {
            my_size += ::protobuf::rt::value_size(6, self.sub_count, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::compute_map_size::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(7, &self.params);
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.path.is_empty() {
            os.write_string(1, &self.path)?;
        }
        if !self.unique.is_empty() {
            os.write_string(2, &self.unique)?;
        }
        if !self.name.is_empty() {
            os.write_string(3, &self.name)?;
        }
        if !self.author.is_empty() {
            os.write_string(4, &self.author)?;
        }
        if self.media_type != 0 {
            os.write_int32(5, self.media_type)?;
        }
        if self.sub_count != 0 {
            os.write_int32(6, self.sub_count)?;
        }
        ::protobuf::rt::write_map_with_cached_sizes::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(7, &self.params, os)?;
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MessagePlugin {
        MessagePlugin::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "path",
                |m: &MessagePlugin| { &m.path },
                |m: &mut MessagePlugin| { &mut m.path },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "unique",
                |m: &MessagePlugin| { &m.unique },
                |m: &mut MessagePlugin| { &mut m.unique },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &MessagePlugin| { &m.name },
                |m: &mut MessagePlugin| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "author",
                |m: &MessagePlugin| { &m.author },
                |m: &mut MessagePlugin| { &mut m.author },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "media_type",
                |m: &MessagePlugin| { &m.media_type },
                |m: &mut MessagePlugin| { &mut m.media_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "sub_count",
                |m: &MessagePlugin| { &m.sub_count },
                |m: &mut MessagePlugin| { &mut m.sub_count },
            ));
            fields.push(::protobuf::reflect::accessor::make_map_accessor::<_, ::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(
                "params",
                |m: &MessagePlugin| { &m.params },
                |m: &mut MessagePlugin| { &mut m.params },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MessagePlugin>(
                "MessagePlugin",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MessagePlugin {
        static instance: ::protobuf::rt::LazyV2<MessagePlugin> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MessagePlugin::new)
    }
}

impl ::protobuf::Clear for MessagePlugin {
    fn clear(&mut self) {
        self.path.clear();
        self.unique.clear();
        self.name.clear();
        self.author.clear();
        self.media_type = 0;
        self.sub_count = 0;
        self.params.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MessagePlugin {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MessagePlugin {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct EventMessagePluginAdd {
    // message fields
    pub plugin: ::protobuf::SingularPtrField<MessagePlugin>,
    pub error: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a EventMessagePluginAdd {
    fn default() -> &'a EventMessagePluginAdd {
        <EventMessagePluginAdd as ::protobuf::Message>::default_instance()
    }
}

impl EventMessagePluginAdd {
    pub fn new() -> EventMessagePluginAdd {
        ::std::default::Default::default()
    }

    // .KPProto.Msg.MessagePlugin plugin = 1;


    pub fn get_plugin(&self) -> &MessagePlugin {
        self.plugin.as_ref().unwrap_or_else(|| <MessagePlugin as ::protobuf::Message>::default_instance())
    }
    pub fn clear_plugin(&mut self) {
        self.plugin.clear();
    }

    pub fn has_plugin(&self) -> bool {
        self.plugin.is_some()
    }

    // Param is passed by value, moved
    pub fn set_plugin(&mut self, v: MessagePlugin) {
        self.plugin = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_plugin(&mut self) -> &mut MessagePlugin {
        if self.plugin.is_none() {
            self.plugin.set_default();
        }
        self.plugin.as_mut().unwrap()
    }

    // Take field
    pub fn take_plugin(&mut self) -> MessagePlugin {
        self.plugin.take().unwrap_or_else(|| MessagePlugin::new())
    }

    // string error = 2;


    pub fn get_error(&self) -> &str {
        &self.error
    }
    pub fn clear_error(&mut self) {
        self.error.clear();
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: ::std::string::String) {
        self.error = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_error(&mut self) -> &mut ::std::string::String {
        &mut self.error
    }

    // Take field
    pub fn take_error(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.error, ::std::string::String::new())
    }
}

impl ::protobuf::Message for EventMessagePluginAdd {
    fn is_initialized(&self) -> bool {
        for v in &self.plugin {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.plugin)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.error)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.plugin.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.error.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.error);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.plugin.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.error.is_empty() {
            os.write_string(2, &self.error)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> EventMessagePluginAdd {
        EventMessagePluginAdd::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<MessagePlugin>>(
                "plugin",
                |m: &EventMessagePluginAdd| { &m.plugin },
                |m: &mut EventMessagePluginAdd| { &mut m.plugin },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "error",
                |m: &EventMessagePluginAdd| { &m.error },
                |m: &mut EventMessagePluginAdd| { &mut m.error },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<EventMessagePluginAdd>(
                "EventMessagePluginAdd",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static EventMessagePluginAdd {
        static instance: ::protobuf::rt::LazyV2<EventMessagePluginAdd> = ::protobuf::rt::LazyV2::INIT;
        instance.get(EventMessagePluginAdd::new)
    }
}

impl ::protobuf::Clear for EventMessagePluginAdd {
    fn clear(&mut self) {
        self.plugin.clear();
        self.error.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for EventMessagePluginAdd {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EventMessagePluginAdd {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct EventMessagePluginRemove {
    // message fields
    pub plugin: ::protobuf::SingularPtrField<MessagePlugin>,
    pub error: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a EventMessagePluginRemove {
    fn default() -> &'a EventMessagePluginRemove {
        <EventMessagePluginRemove as ::protobuf::Message>::default_instance()
    }
}

impl EventMessagePluginRemove {
    pub fn new() -> EventMessagePluginRemove {
        ::std::default::Default::default()
    }

    // .KPProto.Msg.MessagePlugin plugin = 1;


    pub fn get_plugin(&self) -> &MessagePlugin {
        self.plugin.as_ref().unwrap_or_else(|| <MessagePlugin as ::protobuf::Message>::default_instance())
    }
    pub fn clear_plugin(&mut self) {
        self.plugin.clear();
    }

    pub fn has_plugin(&self) -> bool {
        self.plugin.is_some()
    }

    // Param is passed by value, moved
    pub fn set_plugin(&mut self, v: MessagePlugin) {
        self.plugin = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_plugin(&mut self) -> &mut MessagePlugin {
        if self.plugin.is_none() {
            self.plugin.set_default();
        }
        self.plugin.as_mut().unwrap()
    }

    // Take field
    pub fn take_plugin(&mut self) -> MessagePlugin {
        self.plugin.take().unwrap_or_else(|| MessagePlugin::new())
    }

    // string error = 2;


    pub fn get_error(&self) -> &str {
        &self.error
    }
    pub fn clear_error(&mut self) {
        self.error.clear();
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: ::std::string::String) {
        self.error = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_error(&mut self) -> &mut ::std::string::String {
        &mut self.error
    }

    // Take field
    pub fn take_error(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.error, ::std::string::String::new())
    }
}

impl ::protobuf::Message for EventMessagePluginRemove {
    fn is_initialized(&self) -> bool {
        for v in &self.plugin {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.plugin)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.error)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.plugin.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.error.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.error);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.plugin.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.error.is_empty() {
            os.write_string(2, &self.error)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> EventMessagePluginRemove {
        EventMessagePluginRemove::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<MessagePlugin>>(
                "plugin",
                |m: &EventMessagePluginRemove| { &m.plugin },
                |m: &mut EventMessagePluginRemove| { &mut m.plugin },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "error",
                |m: &EventMessagePluginRemove| { &m.error },
                |m: &mut EventMessagePluginRemove| { &mut m.error },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<EventMessagePluginRemove>(
                "EventMessagePluginRemove",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static EventMessagePluginRemove {
        static instance: ::protobuf::rt::LazyV2<EventMessagePluginRemove> = ::protobuf::rt::LazyV2::INIT;
        instance.get(EventMessagePluginRemove::new)
    }
}

impl ::protobuf::Clear for EventMessagePluginRemove {
    fn clear(&mut self) {
        self.plugin.clear();
        self.error.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for EventMessagePluginRemove {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EventMessagePluginRemove {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct EventMessagePluginList {
    // message fields
    pub plugins: ::protobuf::RepeatedField<MessagePlugin>,
    pub error: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a EventMessagePluginList {
    fn default() -> &'a EventMessagePluginList {
        <EventMessagePluginList as ::protobuf::Message>::default_instance()
    }
}

impl EventMessagePluginList {
    pub fn new() -> EventMessagePluginList {
        ::std::default::Default::default()
    }

    // repeated .KPProto.Msg.MessagePlugin plugins = 1;


    pub fn get_plugins(&self) -> &[MessagePlugin] {
        &self.plugins
    }
    pub fn clear_plugins(&mut self) {
        self.plugins.clear();
    }

    // Param is passed by value, moved
    pub fn set_plugins(&mut self, v: ::protobuf::RepeatedField<MessagePlugin>) {
        self.plugins = v;
    }

    // Mutable pointer to the field.
    pub fn mut_plugins(&mut self) -> &mut ::protobuf::RepeatedField<MessagePlugin> {
        &mut self.plugins
    }

    // Take field
    pub fn take_plugins(&mut self) -> ::protobuf::RepeatedField<MessagePlugin> {
        ::std::mem::replace(&mut self.plugins, ::protobuf::RepeatedField::new())
    }

    // string error = 2;


    pub fn get_error(&self) -> &str {
        &self.error
    }
    pub fn clear_error(&mut self) {
        self.error.clear();
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: ::std::string::String) {
        self.error = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_error(&mut self) -> &mut ::std::string::String {
        &mut self.error
    }

    // Take field
    pub fn take_error(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.error, ::std::string::String::new())
    }
}

impl ::protobuf::Message for EventMessagePluginList {
    fn is_initialized(&self) -> bool {
        for v in &self.plugins {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.plugins)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.error)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.plugins {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if !self.error.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.error);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.plugins {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if !self.error.is_empty() {
            os.write_string(2, &self.error)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> EventMessagePluginList {
        EventMessagePluginList::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<MessagePlugin>>(
                "plugins",
                |m: &EventMessagePluginList| { &m.plugins },
                |m: &mut EventMessagePluginList| { &mut m.plugins },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "error",
                |m: &EventMessagePluginList| { &m.error },
                |m: &mut EventMessagePluginList| { &mut m.error },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<EventMessagePluginList>(
                "EventMessagePluginList",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static EventMessagePluginList {
        static instance: ::protobuf::rt::LazyV2<EventMessagePluginList> = ::protobuf::rt::LazyV2::INIT;
        instance.get(EventMessagePluginList::new)
    }
}

impl ::protobuf::Clear for EventMessagePluginList {
    fn clear(&mut self) {
        self.plugins.clear();
        self.error.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for EventMessagePluginList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EventMessagePluginList {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct EventMessagePluginUpdate {
    // message fields
    pub plugin: ::protobuf::SingularPtrField<MessagePlugin>,
    pub error: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a EventMessagePluginUpdate {
    fn default() -> &'a EventMessagePluginUpdate {
        <EventMessagePluginUpdate as ::protobuf::Message>::default_instance()
    }
}

impl EventMessagePluginUpdate {
    pub fn new() -> EventMessagePluginUpdate {
        ::std::default::Default::default()
    }

    // .KPProto.Msg.MessagePlugin plugin = 1;


    pub fn get_plugin(&self) -> &MessagePlugin {
        self.plugin.as_ref().unwrap_or_else(|| <MessagePlugin as ::protobuf::Message>::default_instance())
    }
    pub fn clear_plugin(&mut self) {
        self.plugin.clear();
    }

    pub fn has_plugin(&self) -> bool {
        self.plugin.is_some()
    }

    // Param is passed by value, moved
    pub fn set_plugin(&mut self, v: MessagePlugin) {
        self.plugin = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_plugin(&mut self) -> &mut MessagePlugin {
        if self.plugin.is_none() {
            self.plugin.set_default();
        }
        self.plugin.as_mut().unwrap()
    }

    // Take field
    pub fn take_plugin(&mut self) -> MessagePlugin {
        self.plugin.take().unwrap_or_else(|| MessagePlugin::new())
    }

    // string error = 2;


    pub fn get_error(&self) -> &str {
        &self.error
    }
    pub fn clear_error(&mut self) {
        self.error.clear();
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: ::std::string::String) {
        self.error = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_error(&mut self) -> &mut ::std::string::String {
        &mut self.error
    }

    // Take field
    pub fn take_error(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.error, ::std::string::String::new())
    }
}

impl ::protobuf::Message for EventMessagePluginUpdate {
    fn is_initialized(&self) -> bool {
        for v in &self.plugin {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.plugin)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.error)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.plugin.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.error.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.error);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.plugin.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.error.is_empty() {
            os.write_string(2, &self.error)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> EventMessagePluginUpdate {
        EventMessagePluginUpdate::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<MessagePlugin>>(
                "plugin",
                |m: &EventMessagePluginUpdate| { &m.plugin },
                |m: &mut EventMessagePluginUpdate| { &mut m.plugin },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "error",
                |m: &EventMessagePluginUpdate| { &m.error },
                |m: &mut EventMessagePluginUpdate| { &mut m.error },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<EventMessagePluginUpdate>(
                "EventMessagePluginUpdate",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static EventMessagePluginUpdate {
        static instance: ::protobuf::rt::LazyV2<EventMessagePluginUpdate> = ::protobuf::rt::LazyV2::INIT;
        instance.get(EventMessagePluginUpdate::new)
    }
}

impl ::protobuf::Clear for EventMessagePluginUpdate {
    fn clear(&mut self) {
        self.plugin.clear();
        self.error.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for EventMessagePluginUpdate {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EventMessagePluginUpdate {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1aproto/msg/msg_plugin.proto\x12\x0bKPProto.Msg\"\x9e\x02\n\rMessage\
    Plugin\x12\x12\n\x04path\x18\x01\x20\x01(\tR\x04path\x12\x16\n\x06unique\
    \x18\x02\x20\x01(\tR\x06unique\x12\x12\n\x04name\x18\x03\x20\x01(\tR\x04\
    name\x12\x16\n\x06author\x18\x04\x20\x01(\tR\x06author\x12\x1d\n\nmedia_\
    type\x18\x05\x20\x01(\x05R\tmediaType\x12\x1b\n\tsub_count\x18\x06\x20\
    \x01(\x05R\x08subCount\x12>\n\x06params\x18\x07\x20\x03(\x0b2&.KPProto.M\
    sg.MessagePlugin.ParamsEntryR\x06params\x1a9\n\x0bParamsEntry\x12\x10\n\
    \x03key\x18\x01\x20\x01(\tR\x03key\x12\x14\n\x05value\x18\x02\x20\x01(\t\
    R\x05value:\x028\x01\"a\n\x15EventMessagePluginAdd\x122\n\x06plugin\x18\
    \x01\x20\x01(\x0b2\x1a.KPProto.Msg.MessagePluginR\x06plugin\x12\x14\n\
    \x05error\x18\x02\x20\x01(\tR\x05error\"d\n\x18EventMessagePluginRemove\
    \x122\n\x06plugin\x18\x01\x20\x01(\x0b2\x1a.KPProto.Msg.MessagePluginR\
    \x06plugin\x12\x14\n\x05error\x18\x02\x20\x01(\tR\x05error\"d\n\x16Event\
    MessagePluginList\x124\n\x07plugins\x18\x01\x20\x03(\x0b2\x1a.KPProto.Ms\
    g.MessagePluginR\x07plugins\x12\x14\n\x05error\x18\x02\x20\x01(\tR\x05er\
    ror\"d\n\x18EventMessagePluginUpdate\x122\n\x06plugin\x18\x01\x20\x01(\
    \x0b2\x1a.KPProto.Msg.MessagePluginR\x06plugin\x12\x14\n\x05error\x18\
    \x02\x20\x01(\tR\x05errorB2Z0github.com/bytelang/kplayer/types/core/prot\
    o/msgJ\xf0\x07\n\x06\x12\x04\0\0\"\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\
    \x08\n\x01\x02\x12\x03\x02\0\x14\n\x08\n\x01\x08\x12\x03\x04\0G\n\t\n\
    \x02\x08\x0b\x12\x03\x04\0G\n\n\n\x02\x04\0\x12\x04\x06\0\x0e\x01\n\n\n\
    \x03\x04\0\x01\x12\x03\x06\x08\x15\n\x0b\n\x04\x04\0\x02\0\x12\x03\x07\
    \x02\x12\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x07\x02\x08\n\x0c\n\x05\x04\
    \0\x02\0\x01\x12\x03\x07\t\r\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x07\x10\
    \x11\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x08\x02\x14\n\x0c\n\x05\x04\0\x02\
    \x01\x05\x12\x03\x08\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x08\t\
    \x0f\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x08\x12\x13\n\x0b\n\x04\x04\0\
    \x02\x02\x12\x03\t\x02\x12\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\t\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\t\t\r\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03\t\x10\x11\n\x0b\n\x04\x04\0\x02\x03\x12\x03\n\x02\x14\n\
    \x0c\n\x05\x04\0\x02\x03\x05\x12\x03\n\x02\x08\n\x0c\n\x05\x04\0\x02\x03\
    \x01\x12\x03\n\t\x0f\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\n\x12\x13\n\
    \x0b\n\x04\x04\0\x02\x04\x12\x03\x0b\x02\x17\n\x0c\n\x05\x04\0\x02\x04\
    \x05\x12\x03\x0b\x02\x07\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\x0b\x08\
    \x12\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x0b\x15\x16\n\x0b\n\x04\x04\0\
    \x02\x05\x12\x03\x0c\x02\x16\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\x0c\
    \x02\x07\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\x0c\x08\x11\n\x0c\n\x05\
    \x04\0\x02\x05\x03\x12\x03\x0c\x14\x15\n\x0b\n\x04\x04\0\x02\x06\x12\x03\
    \r\x02!\n\x0c\n\x05\x04\0\x02\x06\x06\x12\x03\r\x02\x15\n\x0c\n\x05\x04\
    \0\x02\x06\x01\x12\x03\r\x16\x1c\n\x0c\n\x05\x04\0\x02\x06\x03\x12\x03\r\
    \x1f\x20\n\n\n\x02\x04\x01\x12\x04\x10\0\x13\x01\n\n\n\x03\x04\x01\x01\
    \x12\x03\x10\x08\x1d\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x11\x02\x1b\n\x0c\
    \n\x05\x04\x01\x02\0\x06\x12\x03\x11\x02\x0f\n\x0c\n\x05\x04\x01\x02\0\
    \x01\x12\x03\x11\x10\x16\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x11\x19\
    \x1a\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\x12\x02\x13\n\x0c\n\x05\x04\x01\
    \x02\x01\x05\x12\x03\x12\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\
    \x12\t\x0e\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x12\x11\x12\n\n\n\x02\
    \x04\x02\x12\x04\x15\0\x18\x01\n\n\n\x03\x04\x02\x01\x12\x03\x15\x08\x20\
    \n\x0b\n\x04\x04\x02\x02\0\x12\x03\x16\x02\x1b\n\x0c\n\x05\x04\x02\x02\0\
    \x06\x12\x03\x16\x02\x0f\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x16\x10\
    \x16\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03\x16\x19\x1a\n\x0b\n\x04\x04\
    \x02\x02\x01\x12\x03\x17\x02\x13\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\x03\
    \x17\x02\x08\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03\x17\t\x0e\n\x0c\n\
    \x05\x04\x02\x02\x01\x03\x12\x03\x17\x11\x12\n\n\n\x02\x04\x03\x12\x04\
    \x1a\0\x1d\x01\n\n\n\x03\x04\x03\x01\x12\x03\x1a\x08\x1e\n\x0b\n\x04\x04\
    \x03\x02\0\x12\x03\x1b\x02%\n\x0c\n\x05\x04\x03\x02\0\x04\x12\x03\x1b\
    \x02\n\n\x0c\n\x05\x04\x03\x02\0\x06\x12\x03\x1b\x0b\x18\n\x0c\n\x05\x04\
    \x03\x02\0\x01\x12\x03\x1b\x19\x20\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03\
    \x1b#$\n\x0b\n\x04\x04\x03\x02\x01\x12\x03\x1c\x02\x13\n\x0c\n\x05\x04\
    \x03\x02\x01\x05\x12\x03\x1c\x02\x08\n\x0c\n\x05\x04\x03\x02\x01\x01\x12\
    \x03\x1c\t\x0e\n\x0c\n\x05\x04\x03\x02\x01\x03\x12\x03\x1c\x11\x12\n\n\n\
    \x02\x04\x04\x12\x04\x1f\0\"\x01\n\n\n\x03\x04\x04\x01\x12\x03\x1f\x08\
    \x20\n\x0b\n\x04\x04\x04\x02\0\x12\x03\x20\x02\x1b\n\x0c\n\x05\x04\x04\
    \x02\0\x06\x12\x03\x20\x02\x0f\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03\x20\
    \x10\x16\n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03\x20\x19\x1a\n\x0b\n\x04\
    \x04\x04\x02\x01\x12\x03!\x02\x13\n\x0c\n\x05\x04\x04\x02\x01\x05\x12\
    \x03!\x02\x08\n\x0c\n\x05\x04\x04\x02\x01\x01\x12\x03!\t\x0e\n\x0c\n\x05\
    \x04\x04\x02\x01\x03\x12\x03!\x11\x12b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
